const clausesData = [
  // General
  {
    id: 1,
    title: 'Confidentiality Agreement',
    definition: 'A clause that requires parties to keep certain information confidential.',
    text: 'Each party agrees to maintain the confidentiality of proprietary information disclosed during the course of this agreement. The receiving party shall not disclose such information to any third party without the prior written consent of the disclosing party, except as required by law. The obligation of confidentiality shall survive the termination of this agreement for a period of five years.',
    category: 'General',
  },
  {
    id: 2,
    title: 'Termination of Agreement',
    definition: 'A clause that outlines the conditions under which an agreement can be terminated.',
    text: 'This agreement may be terminated by either party upon 30 days written notice to the other party. Additionally, this agreement may be terminated immediately by either party if the other party breaches any material term or condition of this agreement and fails to cure such breach within 10 days of receiving written notice of the breach.',
    category: 'General',
  },
  {
    id: 3,
    title: 'Indemnification',
    definition: 'A clause that requires one party to compensate the other for certain damages or losses.',
    text: 'Party A agrees to indemnify and hold harmless Party B from any claims, damages, or expenses, including reasonable attorney fees, arising out of or related to Party A’s breach of this agreement, negligence, or willful misconduct. This indemnification obligation shall survive the termination of this agreement.',
    category: 'General',
  },
  {
    id: 46,
    title: 'Assignment',
    definition: 'A clause that specifies whether the parties can assign their rights or obligations under the agreement to third parties.',
    text: 'Neither party may assign its rights or obligations under this agreement without the prior written consent of the other party. Any attempted assignment without such consent will be null and void.',
    category: 'General',
  },
  {
    id: 47,
    title: 'Force Majeure',
    definition: 'A clause that frees both parties from liability in the event of extraordinary events or circumstances beyond their control.',
    text: 'Neither party shall be liable for any failure to perform its obligations under this agreement due to events beyond its reasonable control, including acts of God, war, terrorism, civil unrest, natural disasters, strikes, or governmental action.',
    category: 'General',
  },
  {
    id: 48,
    title: 'Governing Law',
    definition: 'A clause that specifies which jurisdiction’s laws will govern the agreement.',
    text: 'This agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law principles.',
    category: 'General',
  },
  // Finance
  {
    id: 4,
    title: 'Payment Terms',
    definition: 'A clause that specifies the payment terms and conditions.',
    text: 'Payments are due within 30 days of receipt of invoice. Late payments will incur a 1.5% monthly interest charge. In the event of a dispute over an invoice, the undisputed portion shall be paid in accordance with the terms, and the parties shall work in good faith to resolve the disputed portion promptly.',
    category: 'Finance',
  },
  {
    id: 5,
    title: 'Late Payment Penalties',
    definition: 'A clause that outlines penalties for late payments.',
    text: 'If payment is not received by the due date, a late fee of $50 will be applied to the outstanding balance. Additionally, the unpaid amount will accrue interest at a rate of 1.5% per month until paid in full. The supplier reserves the right to suspend performance of services or delivery of goods if payments are not timely made.',
    category: 'Finance',
  },
  {
    id: 6,
    title: 'Price Adjustment',
    definition: 'A clause that allows for changes in price under certain conditions.',
    text: 'Prices are subject to adjustment in the event of changes in market conditions, including increases in material costs, labor rates, and other factors beyond the control of the supplier. Any price adjustment shall be communicated in writing at least 30 days in advance and shall be subject to the agreement of both parties.',
    category: 'Finance',
  },
  {
    id: 49,
    title: 'Advance Payments',
    definition: 'A clause that specifies if advance payments are required and under what conditions.',
    text: 'The client shall make an advance payment of 25% of the total contract value upon signing this agreement. The remaining balance shall be paid in accordance with the payment terms specified in this agreement.',
    category: 'Finance',
  },
  {
    id: 50,
    title: 'Refund Policy',
    definition: 'A clause that outlines the conditions under which refunds will be issued.',
    text: 'Refunds will be issued only for services not rendered or products not delivered, provided that a request for a refund is made within 30 days of payment. No refunds will be issued for services or products that have already been delivered and accepted.',
    category: 'Finance',
  },
  {
    id: 51,
    title: 'Tax Obligations',
    definition: 'A clause that specifies the tax responsibilities of each party.',
    text: 'Each party shall be responsible for its own tax obligations arising from this agreement. The supplier shall be responsible for all taxes related to the provision of goods or services, and the client shall be responsible for all taxes related to the receipt of goods or services.',
    category: 'Finance',
  },
  // Employment
  {
    id: 7,
    title: 'Non-Competition Agreement',
    definition: 'A clause that restricts an employee from competing with the employer after leaving the company.',
    text: 'The employee agrees not to engage in any business activities that directly compete with the employer for a period of one year after termination of employment within a 50-mile radius of the employer’s primary place of business. This restriction includes, but is not limited to, starting a competing business, working for a competitor, or soliciting the employer’s customers.',
    category: 'Employment',
  },
  {
    id: 8,
    title: 'Non-Solicitation of Employees',
    definition: 'A clause that prevents an employee from soliciting the employer’s clients or employees after leaving the company.',
    text: 'The employee agrees not to solicit or attempt to solicit any of the employer’s clients or employees for a period of two years following termination of employment. This includes directly or indirectly recruiting, encouraging, or inducing any employee to leave their employment with the employer.',
    category: 'Employment',
  },
  {
    id: 9,
    title: 'Severance Pay',
    definition: 'A clause that specifies the severance pay an employee will receive upon termination.',
    text: 'In the event of termination without cause, the employee will receive severance pay equivalent to three months of their current salary, payable in accordance with the employer’s regular payroll schedule. The employee will also be entitled to continued health insurance benefits for the severance period, subject to the terms of the employer’s health insurance plan.',
    category: 'Employment',
  },
  {
    id: 52,
    title: 'Probation Period',
    definition: 'A clause that defines the initial probation period for new employees.',
    text: 'All new employees will be subject to a probationary period of six months. During this period, either party may terminate the employment relationship without cause and with one week’s notice.',
    category: 'Employment',
  },
  {
    id: 53,
    title: 'Employee Benefits',
    definition: 'A clause that outlines the benefits provided to employees.',
    text: 'The employer shall provide the following benefits to the employee: health insurance, dental insurance, vision insurance, life insurance, and a 401(k) retirement plan with company matching. Eligibility for these benefits shall commence on the first day of the month following 60 days of employment.',
    category: 'Employment',
  },
  {
    id: 54,
    title: 'Performance Reviews',
    definition: 'A clause that specifies the schedule and process for employee performance reviews.',
    text: 'Employee performance reviews will be conducted annually. The reviews will assess the employee’s performance against established goals and objectives. The results of the performance review may impact the employee’s salary, bonuses, and eligibility for promotions.',
    category: 'Employment',
  },
  // Intellectual Property
  {
    id: 10,
    title: 'Intellectual Property Ownership',
    definition: 'A clause that outlines the ownership of intellectual property created during the course of the agreement.',
    text: 'All intellectual property, including but not limited to inventions, designs, and developments, created by the employee during their employment shall be the exclusive property of the employer. The employee agrees to execute all documents necessary to assign such rights to the employer and to cooperate with the employer in securing intellectual property protection.',
    category: 'Intellectual Property',
  },
  {
    id: 11,
    title: 'Assignment of Patents',
    definition: 'A clause that assigns patent rights to a particular party.',
    text: 'The employee agrees to assign all rights, title, and interest in any patents developed during the course of their employment to the employer. The employee will promptly disclose any such inventions to the employer and will assist the employer in obtaining and enforcing patent rights for such inventions.',
    category: 'Intellectual Property',
  },
  {
    id: 12,
    title: 'Use of Trademarks',
    definition: 'A clause that outlines the terms under which trademarks can be used.',
    text: 'The licensee is granted a non-exclusive license to use the licensor’s trademarks in connection with the promotion and sale of the licensed products. The licensee agrees to use the trademarks in accordance with the licensor’s trademark guidelines and to cease using the trademarks upon termination of this agreement.',
    category: 'Intellectual Property',
  },
  {
    id: 55,
    title: 'Copyright Assignment',
    definition: 'A clause that assigns copyright ownership to a particular party.',
    text: 'The employee agrees to assign all rights, title, and interest in any works of authorship created during the course of their employment to the employer. This includes all copyrights and any renewals or extensions thereof. The employee will cooperate with the employer in registering and enforcing these copyrights.',
    category: 'Intellectual Property',
  },
  {
    id: 56,
    title: 'License Grant',
    definition: 'A clause that grants a license to use certain intellectual property.',
    text: 'The licensor grants the licensee a non-exclusive, non-transferable license to use the licensor’s intellectual property solely for the purpose of [specified purpose]. The licensee agrees not to modify, distribute, or create derivative works based on the intellectual property without the licensor’s prior written consent.',
    category: 'Intellectual Property',
  },
  {
    id: 57,
    title: 'Confidentiality of Intellectual Property',
    definition: 'A clause that requires parties to keep certain intellectual property confidential.',
    text: 'The receiving party agrees to maintain the confidentiality of the disclosing party’s intellectual property and to use it only for the purposes authorized by the disclosing party. The receiving party shall not disclose such intellectual property to any third party without the prior written consent of the disclosing party.',
    category: 'Intellectual Property',
  },
  // Dispute Resolution
  {
    id: 13,
    title: 'Arbitration',
    definition: 'A clause that requires disputes to be resolved through arbitration rather than litigation.',
    text: 'Any disputes arising out of or relating to this agreement shall be resolved by binding arbitration in accordance with the rules of the American Arbitration Association. The arbitration shall be conducted in [specified location], and the arbitrator’s decision shall be final and binding. Each party shall bear its own costs and expenses of the arbitration.',
    category: 'Dispute Resolution',
  },
  {
    id: 14,
    title: 'Governing Law',
    definition: 'A clause that specifies which jurisdiction’s laws will govern the agreement.',
    text: 'This agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law principles. Any legal action arising out of this agreement shall be brought in the state or federal courts located in [specified county], California.',
    category: 'Dispute Resolution',
  },
  {
    id: 15,
    title: 'Jurisdiction',
    definition: 'A clause that specifies the jurisdiction in which disputes will be resolved.',
    text: 'The parties agree to submit to the exclusive jurisdiction of the courts of the State of New York for any disputes arising out of or relating to this agreement. Each party hereby waives any objection to the personal jurisdiction or venue of such courts.',
    category: 'Dispute Resolution',
  },
  {
    id: 58,
    title: 'Mediation',
    definition: 'A clause that requires disputes to be resolved through mediation before proceeding to arbitration or litigation.',
    text: 'In the event of a dispute arising out of or relating to this agreement, the parties agree to first attempt to resolve the dispute through mediation in accordance with the rules of the American Arbitration Association. If the dispute is not resolved within 30 days after the initiation of mediation, either party may proceed to arbitration or litigation.',
    category: 'Dispute Resolution',
  },
  {
    id: 59,
    title: 'Dispute Escalation',
    definition: 'A clause that outlines the process for escalating disputes within the parties’ organizations before seeking external resolution.',
    text: 'The parties agree to escalate any disputes arising out of or relating to this agreement through their respective management chains. If the dispute is not resolved within 30 days after escalation to senior management, either party may proceed to mediation, arbitration, or litigation as specified in this agreement.',
    category: 'Dispute Resolution',
  },
  {
    id: 60,
    title: 'Cost of Dispute Resolution',
    definition: 'A clause that specifies how the costs of dispute resolution will be allocated between the parties.',
    text: 'Each party shall bear its own costs and expenses in connection with any dispute resolution process, including mediation, arbitration, or litigation. The parties agree to share equally the costs of any mediator or arbitrator fees, as well as any administrative fees associated with the dispute resolution process.',
    category: 'Dispute Resolution',
  },
  // Liability
  {
    id: 16,
    title: 'Limitation of Liability',
    definition: 'A clause that limits the amount of damages one party can be held liable for.',
    text: 'In no event shall either party be liable for any indirect, incidental, special, or consequential damages arising out of or related to this agreement, even if such party has been advised of the possibility of such damages. The total liability of either party for any claims arising out of or related to this agreement shall not exceed the amount paid by the client to the service provider in the twelve months preceding the event giving rise to the claim.',
    category: 'Liability',
  },
  {
    id: 17,
    title: 'Force Majeure',
    definition: 'A clause that frees both parties from liability in the event of extraordinary events or circumstances beyond their control.',
    text: 'Neither party shall be liable for any failure to perform its obligations under this agreement due to events beyond its reasonable control, including, but not limited to, acts of God, war, terrorism, civil unrest, natural disasters, strikes, or governmental action. The affected party shall notify the other party of the force majeure event and its expected duration promptly.',
    category: 'Liability',
  },
  {
    id: 18,
    title: 'Disclaimer of Warranties',
    definition: 'A clause that disclaims certain warranties.',
    text: 'The service is provided "as is" without any warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability or fitness for a particular purpose. The provider does not warrant that the service will be uninterrupted, error-free, or free of viruses or other harmful components.',
    category: 'Liability',
  },
  {
    id: 61,
    title: 'Liability Cap',
    definition: 'A clause that places a cap on the amount of damages one party can be held liable for.',
    text: 'The total liability of either party for any and all claims arising out of or related to this agreement, whether in contract, tort, or otherwise, shall not exceed the total amount paid by the client to the service provider under this agreement.',
    category: 'Liability',
  },
  {
    id: 62,
    title: 'Exclusion of Consequential Damages',
    definition: 'A clause that excludes liability for consequential damages.',
    text: 'In no event shall either party be liable for any indirect, incidental, special, or consequential damages, including lost profits, revenue, or data, arising out of or related to this agreement, even if such party has been advised of the possibility of such damages.',
    category: 'Liability',
  },
  {
    id: 63,
    title: 'Indemnity for Third-Party Claims',
    definition: 'A clause that requires one party to indemnify the other for third-party claims.',
    text: 'Party A agrees to indemnify, defend, and hold harmless Party B from and against any and all claims, damages, liabilities, costs, and expenses, including reasonable attorney’s fees, arising out of or related to any third-party claims resulting from Party A’s breach of this agreement or negligence.',
    category: 'Liability',
  },
  // Sales and Marketing
  {
    id: 19,
    title: 'Exclusive Dealership',
    definition: 'A clause that grants exclusive rights to a dealer to sell a manufacturer’s products in a specified territory.',
    text: 'The manufacturer grants the dealer exclusive rights to sell its products within the specified territory for a period of two years. The dealer agrees to use its best efforts to promote and sell the products and to meet the minimum sales targets specified in Exhibit A.',
    category: 'Sales and Marketing',
  },
  {
    id: 20,
    title: 'Sales Targets',
    definition: 'A clause that sets sales targets for a dealer or distributor.',
    text: 'The dealer agrees to achieve a minimum sales target of $1 million per quarter during the term of this agreement. If the dealer fails to meet the sales target for two consecutive quarters, the manufacturer reserves the right to terminate the exclusive dealership rights.',
    category: 'Sales and Marketing',
  },
  {
    id: 21,
    title: 'Marketing Support',
    definition: 'A clause that outlines the marketing support provided by the manufacturer to the dealer or distributor.',
    text: 'The manufacturer agrees to provide the dealer with marketing materials and support to promote the products in the specified territory. This includes, but is not limited to, brochures, product samples, and advertising funds as outlined in Exhibit B. The dealer agrees to submit quarterly marketing reports detailing their promotional activities.',
    category: 'Sales and Marketing',
  },
  {
    id: 64,
    title: 'Resale Price Maintenance',
    definition: 'A clause that sets the minimum resale price for products sold by the dealer or distributor.',
    text: 'The dealer agrees to sell the manufacturer’s products at or above the minimum resale price specified in Exhibit C. The manufacturer reserves the right to terminate this agreement if the dealer sells the products below the minimum resale price.',
    category: 'Sales and Marketing',
  },
  {
    id: 65,
    title: 'Product Returns',
    definition: 'A clause that outlines the conditions under which product returns will be accepted.',
    text: 'The dealer may return unsold products to the manufacturer within 90 days of delivery, provided that the products are in their original packaging and in resalable condition. The manufacturer will issue a credit to the dealer’s account for the returned products, less a restocking fee of 10%.',
    category: 'Sales and Marketing',
  },
  {
    id: 66,
    title: 'Advertising Funds',
    definition: 'A clause that specifies the advertising funds provided by the manufacturer to the dealer.',
    text: 'The manufacturer agrees to provide the dealer with an annual advertising fund of $10,000 to promote the manufacturer’s products. The dealer shall submit receipts and documentation for all advertising expenses to the manufacturer for reimbursement from the advertising fund.',
    category: 'Sales and Marketing',
  },
  // Real Estate
  {
    id: 22,
    title: 'Lease Agreement',
    definition: 'A clause that outlines the terms and conditions of a lease agreement.',
    text: 'The tenant agrees to lease the premises located at [address] for a term of one year at a monthly rent of $1,500, payable on the first day of each month. The tenant shall also pay a security deposit of $1,500, which shall be refunded upon termination of the lease, less any deductions for damages or unpaid rent.',
    category: 'Real Estate',
  },
  {
    id: 23,
    title: 'Maintenance Obligations',
    definition: 'A clause that specifies the maintenance obligations of the landlord and tenant.',
    text: 'The landlord is responsible for maintaining the structural integrity of the building, including the roof, walls, and foundation. The tenant is responsible for routine maintenance and repairs, including plumbing, electrical systems, and HVAC. The tenant agrees to keep the premises in a clean and sanitary condition and to notify the landlord promptly of any repairs needed.',
    category: 'Real Estate',
  },
  {
    id: 24,
    title: 'Sublease Agreement',
    definition: 'A clause that allows or restricts the tenant’s ability to sublease the premises.',
    text: 'The tenant may not sublease the premises without the prior written consent of the landlord. Any sublease agreement shall be subject to the terms and conditions of this lease, and the tenant shall remain fully responsible for all obligations under this lease, including the payment of rent.',
    category: 'Real Estate',
  },
  {
    id: 67,
    title: 'Option to Renew',
    definition: 'A clause that grants the tenant the option to renew the lease for an additional term.',
    text: 'The tenant shall have the option to renew this lease for an additional term of one year upon providing written notice to the landlord at least 60 days prior to the expiration of the current term. The renewal term shall be on the same terms and conditions as this lease, except that the monthly rent shall be subject to adjustment as agreed by the parties.',
    category: 'Real Estate',
  },
  {
    id: 68,
    title: 'Rent Escalation',
    definition: 'A clause that provides for periodic increases in rent.',
    text: 'The monthly rent shall increase by 3% annually on the anniversary of the commencement date of this lease. The landlord shall provide the tenant with written notice of the new rent amount at least 30 days prior to the effective date of the increase.',
    category: 'Real Estate',
  },
  {
    id: 69,
    title: 'Common Area Maintenance',
    definition: 'A clause that outlines the tenant’s responsibility for common area maintenance charges.',
    text: 'The tenant shall pay its proportionate share of common area maintenance (CAM) charges, including but not limited to, landscaping, snow removal, and parking lot maintenance. The landlord shall provide the tenant with an itemized statement of CAM charges annually, and the tenant shall pay its share within 30 days of receipt of the statement.',
    category: 'Real Estate',
  },
  // Data Protection
  {
    id: 25,
    title: 'Data Privacy',
    definition: 'A clause that outlines the obligations related to the protection of personal data.',
    text: 'The parties agree to comply with all applicable data protection laws and regulations, including the General Data Protection Regulation (GDPR). Each party shall implement appropriate technical and organizational measures to protect personal data against unauthorized access, disclosure, alteration, or destruction.',
    category: 'Data Protection',
  },
  {
    id: 26,
    title: 'Data Breach Notification',
    definition: 'A clause that specifies the procedure for notifying parties in the event of a data breach.',
    text: 'In the event of a data breach, the affected party must notify the other party within 72 hours of becoming aware of the breach. The notification shall include a description of the nature of the breach, the categories and approximate number of individuals affected, and the measures taken or proposed to address the breach and mitigate its effects.',
    category: 'Data Protection',
  },
  {
    id: 27,
    title: 'Data Retention',
    definition: 'A clause that outlines the policies for retaining and disposing of data.',
    text: 'The parties agree to retain data only for as long as necessary to fulfill the purposes of this agreement. Upon termination of this agreement or upon request, each party shall securely dispose of or return any personal data in its possession, except where retention is required by law.',
    category: 'Data Protection',
  },
  {
    id: 70,
    title: 'Data Processing Agreement',
    definition: 'A clause that outlines the terms for processing personal data on behalf of another party.',
    text: 'The data processor agrees to process personal data only in accordance with the instructions of the data controller and for the purposes specified in this agreement. The data processor shall implement appropriate technical and organizational measures to protect personal data and shall not transfer personal data to any third party without the prior written consent of the data controller.',
    category: 'Data Protection',
  },
  {
    id: 71,
    title: 'Access to Data',
    definition: 'A clause that specifies the conditions under which one party can access data held by the other party.',
    text: 'The data controller shall have the right to access and retrieve personal data held by the data processor at any time upon providing reasonable notice. The data processor agrees to provide access to the personal data and any related records, documents, and systems as necessary to facilitate the data controller’s access.',
    category: 'Data Protection',
  },
  {
    id: 72,
    title: 'Data Subject Rights',
    definition: 'A clause that outlines the rights of data subjects and the responsibilities of the parties in relation to those rights.',
    text: 'The parties agree to respect the rights of data subjects, including the right to access, rectify, erase, and restrict the processing of their personal data. The data processor shall promptly notify the data controller of any requests received from data subjects and shall assist the data controller in responding to such requests.',
    category: 'Data Protection',
  },
  // Compliance
  {
    id: 28,
    title: 'Regulatory Compliance',
    definition: 'A clause that requires compliance with relevant laws and regulations.',
    text: 'The parties agree to comply with all applicable laws and regulations, including those related to anti-corruption, export control, and environmental protection. Each party shall obtain and maintain all necessary licenses, permits, and approvals required for the performance of its obligations under this agreement.',
    category: 'Compliance',
  },
  {
    id: 29,
    title: 'Anti-Bribery',
    definition: 'A clause that prohibits bribery and corruption.',
    text: 'The parties agree not to engage in any form of bribery or corruption in connection with this agreement. Each party shall maintain adequate procedures designed to prevent bribery and comply with applicable anti-bribery laws, including the U.S. Foreign Corrupt Practices Act and the UK Bribery Act.',
    category: 'Compliance',
  },
  {
    id: 30,
    title: 'Audit Rights',
    definition: 'A clause that grants one party the right to audit the other party’s compliance with the agreement.',
    text: 'The company reserves the right to audit the vendor’s compliance with this agreement upon reasonable notice and during normal business hours. The vendor agrees to provide access to relevant records, documents, and personnel as necessary to facilitate the audit. Any deficiencies identified during the audit shall be promptly addressed by the vendor.',
    category: 'Compliance',
  },
  {
    id: 73,
    title: 'Export Control',
    definition: 'A clause that requires compliance with export control laws and regulations.',
    text: 'The parties agree to comply with all applicable export control laws and regulations, including those of the United States and the European Union. Neither party shall export or re-export any goods, software, or technology provided under this agreement without obtaining the necessary licenses, permits, and approvals.',
    category: 'Compliance',
  },
  {
    id: 74,
    title: 'Environmental Compliance',
    definition: 'A clause that requires compliance with environmental laws and regulations.',
    text: 'The parties agree to comply with all applicable environmental laws and regulations, including those related to waste management, pollution control, and hazardous materials. Each party shall obtain and maintain all necessary licenses, permits, and approvals required for the performance of its obligations under this agreement.',
    category: 'Compliance',
  },
  {
    id: 75,
    title: 'Health and Safety',
    definition: 'A clause that requires compliance with health and safety laws and regulations.',
    text: 'The parties agree to comply with all applicable health and safety laws and regulations, including those related to workplace safety, occupational health, and emergency preparedness. Each party shall implement appropriate measures to protect the health and safety of its employees, contractors, and visitors.',
    category: 'Compliance',
  },
  // Warranties
  {
    id: 31,
    title: 'Product Warranty',
    definition: 'A clause that provides a warranty for the products being sold.',
    text: 'The seller warrants that the products will be free from defects in materials and workmanship for a period of one year from the date of delivery. If a defect is discovered during the warranty period, the seller will, at its option, repair or replace the defective product or provide a refund of the purchase price.',
    category: 'Warranties',
  },
  {
    id: 32,
    title: 'Service Warranty',
    definition: 'A clause that provides a warranty for the services being provided.',
    text: 'The provider warrants that the services will be performed in a professional and workmanlike manner and will conform to the agreed-upon specifications. If the services do not meet this standard, the provider will re-perform the services at no additional cost to the client.',
    category: 'Warranties',
  },
  {
    id: 33,
    title: 'Warranty Disclaimer',
    definition: 'A clause that disclaims certain warranties.',
    text: 'Except as expressly provided herein, the provider disclaims all other warranties, express or implied, including any implied warranties of merchantability or fitness for a particular purpose. The provider does not warrant that the services will meet the client’s requirements or that the services will be uninterrupted or error-free.',
    category: 'Warranties',
  },
  {
    id: 76,
    title: 'Extended Warranty',
    definition: 'A clause that offers an extended warranty for an additional fee.',
    text: 'The client may purchase an extended warranty for the products for an additional fee. The extended warranty shall extend the warranty period by an additional two years and shall cover all defects in materials and workmanship. The extended warranty must be purchased at the time of the original purchase.',
    category: 'Warranties',
  },
  {
    id: 77,
    title: 'Warranty Exclusions',
    definition: 'A clause that specifies what is not covered by the warranty.',
    text: 'This warranty does not cover damage caused by misuse, abuse, neglect, accident, unauthorized modification, or improper installation. The warranty also does not cover normal wear and tear, cosmetic damage, or damage caused by external factors such as fire, flood, or lightning.',
    category: 'Warranties',
  },
  {
    id: 78,
    title: 'Warranty Claim Procedure',
    definition: 'A clause that outlines the procedure for making a warranty claim.',
    text: 'To make a warranty claim, the client must notify the provider in writing of the defect within the warranty period. The client must provide proof of purchase and a detailed description of the defect. The provider will issue a return authorization number and instructions for returning the defective product. The client is responsible for shipping costs associated with the return of the defective product.',
    category: 'Warranties',
  },
  // Insurance
  {
    id: 34,
    title: 'Insurance Requirements',
    definition: 'A clause that specifies the insurance coverage required by the parties.',
    text: 'The contractor shall maintain general liability insurance with coverage of at least $1 million per occurrence and $2 million in aggregate. The contractor shall also maintain workers’ compensation insurance as required by law. Certificates of insurance evidencing the required coverage shall be provided to the company upon request.',
    category: 'Insurance',
  },
  {
    id: 35,
    title: 'Proof of Insurance',
    definition: 'A clause that requires proof of insurance coverage.',
    text: 'The contractor shall provide the company with certificates of insurance evidencing the required coverage prior to the commencement of services. The certificates shall name the company as an additional insured and shall provide that the insurance shall not be canceled or materially altered without at least 30 days prior written notice to the company.',
    category: 'Insurance',
  },
  {
    id: 36,
    title: 'Subrogation',
    definition: 'A clause that addresses subrogation rights.',
    text: 'The insurance policy shall include a waiver of subrogation in favor of the company. This means that the insurer waives any right to recover any payment it makes on behalf of the insured from the company, even if the company is at fault.',
    category: 'Insurance',
  },
  {
    id: 79,
    title: 'Additional Insured',
    definition: 'A clause that requires one party to name the other party as an additional insured on its insurance policies.',
    text: 'The contractor shall name the company as an additional insured on all liability insurance policies required under this agreement. The additional insured coverage shall apply on a primary and non-contributory basis and shall provide the company with coverage at least as broad as that provided to the contractor.',
    category: 'Insurance',
  },
  {
    id: 80,
    title: 'Notice of Cancellation',
    definition: 'A clause that requires notice to be given in the event of insurance policy cancellation.',
    text: 'The contractor shall provide the company with at least 30 days prior written notice of any cancellation or material change to any insurance policy required under this agreement. In the event of cancellation, the contractor shall obtain replacement coverage that meets the requirements of this agreement and provide the company with certificates of insurance evidencing such coverage.',
    category: 'Insurance',
  },
  {
    id: 81,
    title: 'Self-Insurance',
    definition: 'A clause that allows one party to self-insure rather than obtain traditional insurance coverage.',
    text: 'If the contractor is self-insured, it shall provide the company with evidence of its ability to meet the insurance requirements of this agreement. The contractor shall maintain reserves sufficient to cover any liabilities that may arise under this agreement and shall provide the company with financial statements or other documentation upon request to demonstrate its financial stability.',
    category: 'Insurance',
  },
  // Miscellaneous
  {
    id: 37,
    title: 'Entire Agreement',
    definition: 'A clause that states the agreement constitutes the entire agreement between the parties.',
    text: 'This agreement constitutes the entire agreement between the parties and supersedes all prior understandings or agreements, whether written or oral. No amendment or modification of this agreement shall be valid unless in writing and signed by both parties.',
    category: 'Miscellaneous',
  },
  {
    id: 38,
    title: 'Amendments',
    definition: 'A clause that outlines the procedure for amending the agreement.',
    text: 'Any amendments to this agreement must be in writing and signed by both parties. No oral modifications will be binding. Each party agrees to negotiate in good faith any proposed amendments and to execute a formal written amendment to reflect any agreed-upon changes.',
    category: 'Miscellaneous',
  },
  {
    id: 39,
    title: 'Notices',
    definition: 'A clause that specifies the method and address for sending notices.',
    text: 'All notices under this agreement shall be in writing and shall be deemed to have been duly given when delivered by hand, overnight courier, or registered mail to the addresses specified in this agreement. Notices sent by registered mail shall be deemed received three days after the date of mailing.',
    category: 'Miscellaneous',
  },
  {
    id: 82,
    title: 'Severability',
    definition: 'A clause that ensures the remaining provisions of the agreement remain in effect if any provision is found to be unenforceable.',
    text: 'If any provision of this agreement is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect. The parties agree to negotiate in good faith to replace any invalid or unenforceable provision with a valid and enforceable provision that achieves the intended purpose of the original provision.',
    category: 'Miscellaneous',
  },
  {
    id: 83,
    title: 'Waiver',
    definition: 'A clause that specifies that a party’s failure to enforce a provision of the agreement does not constitute a waiver of that provision.',
    text: 'No waiver of any provision of this agreement shall be effective unless in writing and signed by the party waiving the provision. The failure of either party to enforce any provision of this agreement shall not be construed as a waiver of that provision or any other provision, and shall not prevent that party from enforcing the provision at a later date.',
    category: 'Miscellaneous',
  },
  {
    id: 84,
    title: 'Counterparts',
    definition: 'A clause that allows the agreement to be executed in multiple counterparts.',
    text: 'This agreement may be executed in one or more counterparts, each of which shall be deemed an original and all of which together shall constitute one and the same agreement. Signatures transmitted electronically or by facsimile shall be deemed to be original signatures for all purposes.',
    category: 'Miscellaneous',
  },
  // Performance
  {
    id: 40,
    title: 'Performance Metrics',
    definition: 'A clause that defines the performance metrics for services or products.',
    text: 'The provider agrees to meet the following performance metrics: uptime of 99.9%, response time within 24 hours, and resolution time within 3 business days. Failure to meet these performance metrics may result in service credits or other remedies as specified in the agreement.',
    category: 'Performance',
  },
  {
    id: 41,
    title: 'Service Level Agreement',
    definition: 'A clause that defines the service levels and response times.',
    text: 'The provider agrees to provide support services as defined in the Service Level Agreement (SLA), including 24/7 support and a maximum response time of 2 hours for critical issues. The SLA shall outline the specific service levels, response times, and remedies for failure to meet the service levels.',
    category: 'Performance',
  },
  {
    id: 42,
    title: 'Performance Reviews',
    definition: 'A clause that outlines the schedule and process for performance reviews.',
    text: 'The parties agree to conduct performance reviews every quarter to assess the provider’s compliance with the performance metrics and service levels defined in this agreement. The performance reviews shall include a review of service quality, response times, and any service credits or penalties accrued during the review period.',
    category: 'Performance',
  },
  {
    id: 85,
    title: 'Remedies for Non-Performance',
    definition: 'A clause that specifies the remedies available to the client in the event of non-performance by the provider.',
    text: 'If the provider fails to meet the performance metrics specified in this agreement, the client shall be entitled to service credits as outlined in Exhibit D. If the provider’s non-performance continues for more than 30 days, the client may terminate this agreement for cause and seek any additional remedies available under the law.',
    category: 'Performance',
  },
  {
    id: 86,
    title: 'Continuous Improvement',
    definition: 'A clause that requires the provider to implement continuous improvement practices.',
    text: 'The provider agrees to implement continuous improvement practices to enhance the quality and efficiency of the services provided under this agreement. The provider shall regularly review its performance against the performance metrics and shall implement corrective actions as necessary to achieve and maintain the specified performance levels.',
    category: 'Performance',
  },
  {
    id: 87,
    title: 'Key Performance Indicators',
    definition: 'A clause that defines the key performance indicators (KPIs) for the services provided.',
    text: 'The provider agrees to measure and report on the following key performance indicators (KPIs) on a monthly basis: uptime percentage, average response time, average resolution time, customer satisfaction score, and number of incidents resolved within SLA. The provider shall use the KPI data to identify areas for improvement and to implement corrective actions as necessary.',
    category: 'Performance',
  },
  // Security
  {
    id: 43,
    title: 'Security Requirements',
    definition: 'A clause that specifies the security requirements for data and systems.',
    text: 'The provider agrees to implement and maintain appropriate security measures to protect the confidentiality, integrity, and availability of the data and systems. This includes, but is not limited to, encryption, access controls, and regular security audits. The provider shall promptly notify the company of any security breaches or incidents.',
    category: 'Security',
  },
  {
    id: 44,
    title: 'Security Breach Notification',
    definition: 'A clause that specifies the procedure for notifying parties in the event of a security breach.',
    text: 'In the event of a security breach, the provider must notify the company within 24 hours of discovering the breach. The notification shall include a description of the breach, the data affected, and the steps taken to mitigate the breach. The provider shall cooperate with the company in investigating and responding to the breach.',
    category: 'Security',
  },
  {
    id: 45,
    title: 'Security Audits',
    definition: 'A clause that grants one party the right to conduct security audits.',
    text: 'The company reserves the right to conduct security audits of the provider’s systems and processes upon reasonable notice and during normal business hours. The provider agrees to provide access to relevant records, documents, and personnel as necessary to facilitate the audit. Any deficiencies identified during the audit shall be promptly addressed by the provider.',
    category: 'Security',
  },
  {
    id: 88,
    title: 'Data Encryption',
    definition: 'A clause that specifies the data encryption requirements for protecting sensitive information.',
    text: 'The provider agrees to encrypt all sensitive data at rest and in transit using industry-standard encryption algorithms. The provider shall implement and maintain encryption key management procedures to ensure the security and integrity of the encryption keys. The provider shall promptly notify the company of any breaches or compromises of the encryption keys.',
    category: 'Security',
  },
  {
    id: 89,
    title: 'Access Controls',
    definition: 'A clause that specifies the access control measures required to protect data and systems.',
    text: 'The provider agrees to implement and maintain access control measures to restrict access to data and systems to authorized personnel only. This includes, but is not limited to, multi-factor authentication, role-based access controls, and regular access reviews. The provider shall promptly revoke access for personnel who no longer require access to the data or systems.',
    category: 'Security',
  },
  {
    id: 90,
    title: 'Incident Response',
    definition: 'A clause that specifies the incident response procedures for security breaches.',
    text: 'The provider agrees to implement and maintain an incident response plan to address security breaches and incidents. The incident response plan shall include procedures for identifying, containing, eradicating, and recovering from security incidents. The provider shall conduct regular incident response drills and shall promptly notify the company of any security incidents and the steps taken to mitigate the incident.',
    category: 'Security',
  },
];

export default clausesData;
